name: Docker Image build

on:
  push:
    branches:
      - '**'
      - '!deploy'
  pull_request:
    branches:
      - '**'
      - '!deploy'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build .
